version: '3'
services:
  mysql:
    image: mysql:${mysql_TAG}
    restart: always
    environment:
      DB_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: #test

    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
#    ports:
#      - "3306:3306"
